### ISSUE TITLE
sys-devel/llvm-9.0 ERRORING

### ISSUE THREAD

**Issue by AdamKearn** [FydeOS/overlay-variant-amd64-generic-vmware#1]
While compiling this overlay I experienced this error:
What do you think is going on??

-Adam

```
llvm-9.0_pre361749_p20190714-r10: ninja: build stopped: subcommand failed.
llvm-9.0_pre361749_p20190714-r10:  * ERROR: sys-devel/llvm-9.0_pre361749_p20190714-r10::chromiumos failed (compile phase):
llvm-9.0_pre361749_p20190714-r10:  *   (no error message)
llvm-9.0_pre361749_p20190714-r10:  * 
llvm-9.0_pre361749_p20190714-r10:  * Call stack:
llvm-9.0_pre361749_p20190714-r10:  *     ebuild.sh, line  124:  Called src_compile
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 6215:  Called multilib-minimal_src_compile
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 4295:  Called multilib_foreach_abi 'multilib-minimal_abi_src_compile'
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 4527:  Called multibuild_foreach_variant '_multilib_multibuild_wrapper' 'multilib-minimal_abi_src_compile'
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 4230:  Called _multibuild_run '_multilib_multibuild_wrapper' 'multilib-minimal_abi_src_compile'
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 4228:  Called _multilib_multibuild_wrapper 'multilib-minimal_abi_src_compile'
llvm-9.0_pre361749_p20190714-r10:  *   environment, line  910:  Called multilib-minimal_abi_src_compile
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 4289:  Called multilib_src_compile
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 4739:  Called cmake-utils_src_compile
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 1549:  Called _cmake_execute_optionally 'src_compile'
llvm-9.0_pre361749_p20190714-r10:  *   environment, line  435:  Called enable_cmake-utils_src_compile
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 1955:  Called cmake-utils_src_make
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 1564:  Called _cmake_ninja_src_make
llvm-9.0_pre361749_p20190714-r10:  *   environment, line  491:  Called die
llvm-9.0_pre361749_p20190714-r10:  * The specific snippet of code:
llvm-9.0_pre361749_p20190714-r10:  *       "$@" || die
llvm-9.0_pre361749_p20190714-r10:  * 
llvm-9.0_pre361749_p20190714-r10:  * If you need support, post the output of `emerge --info '=sys-devel/llvm-9.0_pre361749_p20190714-r10::chromiumos'`,
llvm-9.0_pre361749_p20190714-r10:  * the complete build log and the output of `emerge -pqv '=sys-devel/llvm-9.0_pre361749_p20190714-r10::chromiumos'`.
llvm-9.0_pre361749_p20190714-r10:  * The complete build log is located at '/var/log/portage/sys-devel:llvm-9.0_pre361749_p20190714-r10:20190808-195216.log'.
llvm-9.0_pre361749_p20190714-r10:  * For convenience, a symlink to the build log is located at '/var/tmp/portage/sys-devel/llvm-9.0_pre361749_p20190714-r10/temp/build.log'.
llvm-9.0_pre361749_p20190714-r10:  * The ebuild environment file is located at '/var/tmp/portage/sys-devel/llvm-9.0_pre361749_p20190714-r10/temp/environment'.
llvm-9.0_pre361749_p20190714-r10:  * Working directory: '/var/tmp/portage/sys-devel/llvm-9.0_pre361749_p20190714-r10/work/llvm-9.0_pre361749_p20190714-abi_x86_64.amd64'
llvm-9.0_pre361749_p20190714-r10:  * S: '/var/tmp/portage/sys-devel/llvm-9.0_pre361749_p20190714-r10/work/llvm-9.0_pre361749_p20190714'
llvm-9.0_pre361749_p20190714-r10: >>> Failed to emerge sys-devel/llvm-9.0_pre361749_p20190714-r10, Log file:
llvm-9.0_pre361749_p20190714-r10: >>>  '/var/log/portage/sys-devel:llvm-9.0_pre361749_p20190714-r10:20190808-195216.log'
llvm-9.0_pre361749_p20190714-r10: 
llvm-9.0_pre361749_p20190714-r10:  * Messages for package sys-devel/llvm-9.0_pre361749_p20190714-r10:
llvm-9.0_pre361749_p20190714-r10:  * Log file: /var/log/portage/sys-devel:llvm-9.0_pre361749_p20190714-r10:20190808-195216.log
llvm-9.0_pre361749_p20190714-r10: 
llvm-9.0_pre361749_p20190714-r10:  * ERROR: sys-devel/llvm-9.0_pre361749_p20190714-r10::chromiumos failed (compile phase):
llvm-9.0_pre361749_p20190714-r10:  *   (no error message)
llvm-9.0_pre361749_p20190714-r10:  * 
llvm-9.0_pre361749_p20190714-r10:  * Call stack:
llvm-9.0_pre361749_p20190714-r10:  *     ebuild.sh, line  124:  Called src_compile
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 6215:  Called multilib-minimal_src_compile
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 4295:  Called multilib_foreach_abi 'multilib-minimal_abi_src_compile'
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 4527:  Called multibuild_foreach_variant '_multilib_multibuild_wrapper' 'multilib-minimal_abi_src_compile'
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 4230:  Called _multibuild_run '_multilib_multibuild_wrapper' 'multilib-minimal_abi_src_compile'
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 4228:  Called _multilib_multibuild_wrapper 'multilib-minimal_abi_src_compile'
llvm-9.0_pre361749_p20190714-r10:  *   environment, line  910:  Called multilib-minimal_abi_src_compile
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 4289:  Called multilib_src_compile
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 4739:  Called cmake-utils_src_compile
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 1549:  Called _cmake_execute_optionally 'src_compile'
llvm-9.0_pre361749_p20190714-r10:  *   environment, line  435:  Called enable_cmake-utils_src_compile
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 1955:  Called cmake-utils_src_make
llvm-9.0_pre361749_p20190714-r10:  *   environment, line 1564:  Called _cmake_ninja_src_make
llvm-9.0_pre361749_p20190714-r10:  *   environment, line  491:  Called die
llvm-9.0_pre361749_p20190714-r10:  * The specific snippet of code:
llvm-9.0_pre361749_p20190714-r10:  *       "$@" || die
llvm-9.0_pre361749_p20190714-r10:  * 
llvm-9.0_pre361749_p20190714-r10:  * If you need support, post the output of `emerge --info '=sys-devel/llvm-9.0_pre361749_p20190714-r10::chromiumos'`,
llvm-9.0_pre361749_p20190714-r10:  * the complete build log and the output of `emerge -pqv '=sys-devel/llvm-9.0_pre361749_p20190714-r10::chromiumos'`.
llvm-9.0_pre361749_p20190714-r10:  * The complete build log is located at '/var/log/portage/sys-devel:llvm-9.0_pre361749_p20190714-r10:20190808-195216.log'.
llvm-9.0_pre361749_p20190714-r10:  * For convenience, a symlink to the build log is located at '/var/tmp/portage/sys-devel/llvm-9.0_pre361749_p20190714-r10/temp/build.log'.
llvm-9.0_pre361749_p20190714-r10:  * The ebuild environment file is located at '/var/tmp/portage/sys-devel/llvm-9.0_pre361749_p20190714-r10/temp/environment'.
llvm-9.0_pre361749_p20190714-r10:  * Working directory: '/var/tmp/portage/sys-devel/llvm-9.0_pre361749_p20190714-r10/work/llvm-9.0_pre361749_p20190714-abi_x86_64.amd64'
llvm-9.0_pre361749_p20190714-r10:  * S: '/var/tmp/portage/sys-devel/llvm-9.0_pre361749_p20190714-r10/work/llvm-9.0_pre361749_p20190714'
=== Complete: job llvm-9.0_pre361749_p20190714-r10 (108m37.9s) ===
Failed sys-devel/llvm-9.0_pre361749_p20190714-r10 (in 108m37.9s), retrying later.
Pending 5/7, Building 0/0, Retrying 1, [Time 14:40:53 | Elapsed 108m48.9s | Load 7.03 9.99 10.85]
```

I also get this:
```
Traceback (most recent call last):
  File "/mnt/host/source/chromite/bin/setup_board", line 175, in <module>
    DoMain()
  File "/mnt/host/source/chromite/bin/setup_board", line 171, in DoMain
    commandline.ScriptWrapperMain(FindTarget)
  File "/mnt/host/source/chromite/lib/commandline.py", line 961, in ScriptWrapperMain
    ret = target(argv[1:])
  File "/mnt/host/source/chromite/scripts/setup_board.py", line 133, in main
    sysroot.SetupBoard(opts.build_target, opts.accept_licenses, opts.run_config)
  File "/mnt/host/source/chromite/service/sysroot.py", line 174, in SetupBoard
    sysroot = Create(target, run_configs, accept_licenses)
  File "/mnt/host/source/chromite/service/sysroot.py", line 216, in Create
    cros_build_lib.RunCommand(update_chroot)
  File "/mnt/host/source/chromite/lib/cros_build_lib.py", line 628, in RunCommand
    (cmd_result.output, cmd_result.error) = proc.communicate(input)
  File "/usr/lib64/python2.7/subprocess.py", line 480, in communicate
    self.wait()
  File "/usr/lib64/python2.7/subprocess.py", line 1099, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib64/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
  File "/mnt/host/source/chromite/lib/cros_build_lib.py", line 371, in _KillChildProcess
    if not signals.RelaySignal(original_handler, signum, frame):
  File "/mnt/host/source/chromite/lib/signals.py", line 27, in RelaySignal
    handler(signum, frame)
KeyboardInterrupt
ERROR   : Thu Aug  8 14:55:14 PDT 2019
ERROR   :   PGID   PPID    PID     ELAPSED     TIME %CPU COMMAND
ERROR   :      7      4      7  1-02:47:25 00:00:00  0.0 -bash
ERROR   :  62311      7  62311    02:03:19 00:00:00  0.0  \_ /bin/bash ./build_packages --board=amd64-generic_vmware --nousepkg
ERROR   :  62311  62311 109207       00:00 00:00:00  0.0      \_ /bin/bash ./build_packages --board=amd64-generic_vmware --nousepkg
ERROR   :  62311 109207 109208       00:00 00:00:00  0.0          \_ ps f -o pgid,ppid,pid,etime,cputime,%cpu,command
ERROR   : Arguments of 62311: ./build_packages '--board=amd64-generic_vmware' '--nousepkg'
ERROR   : Backtrace:  (most recent call is last)
ERROR   :  build_packages:168:main(), called: die_err_trap  
ERROR   : 
ERROR   : Command failed:
ERROR   :   Command 'setup_board --quiet --board=${FLAGS_board} "${UPDATE_ARGS[@]}"' exited with nonzero code: 1
```

**Comment by yunshansimon** [comment]
Add `>sys-devel/llvm-7.0.1` in `profiles/base/package.mask`

**Comment by AdamKearn** [comment]
I managed to fix it just by emerging `sys-devel/llvm`
However, I getting problems with `GOMA` I think.

I am not sure how to disable it?  Do you know??

```
Starting fast-emerge.
 Building package virtual/target-os virtual/target-os-dev virtual/target-os-factory virtual/target-os-factory-shim virtual/target-os-test chromeos-base/autotest-all on /build/amd64-generic_vmware
Calculating deps...
parallel_emerge: Unhandled exception:
Traceback (most recent call last):
  File "/mnt/host/source/chromite/bin/parallel_emerge", line 175, in <module>
    DoMain()
  File "/mnt/host/source/chromite/bin/parallel_emerge", line 171, in DoMain
    commandline.ScriptWrapperMain(FindTarget)
  File "/mnt/host/source/chromite/lib/commandline.py", line 961, in ScriptWrapperMain
    ret = target(argv[1:])
  File "/mnt/host/source/chromite/scripts/parallel_emerge.py", line 29, in main
    PARALLEL_EMERGE_OLD.main(argv)
  File "/mnt/host/source/chromite/scripts/parallel_emerge_old.py", line 1899, in main
    return real_main(argv)
  File "/mnt/host/source/chromite/scripts/parallel_emerge_old.py", line 1943, in real_main
    deps_tree, deps_info = deps.GenDependencyTree()
  File "/mnt/host/source/chromite/scripts/parallel_emerge_old.py", line 533, in GenDependencyTree
    assert pkg.root == root
AssertionError
ERROR   : Sun Aug 11 15:02:50 PDT 2019
ERROR   :   PGID   PPID    PID     ELAPSED     TIME %CPU COMMAND
ERROR   :      7      4      7       43:55 00:00:00  0.0 -bash
ERROR   :  67591      7  67591       04:08 00:00:00  0.0  \_ /bin/bash ./build_packages --board=amd64-generic_vmware --nousepkg
ERROR   :  67591  67591 119081       00:00 00:00:00  0.0      \_ /bin/bash ./build_packages --board=amd64-generic_vmware --nousepkg
ERROR   :  67591 119081 119082       00:00 00:00:00  0.0          \_ ps f -o pgid,ppid,pid,etime,cputime,%cpu,command
ERROR   : Arguments of 67591: ./build_packages '--board=amd64-generic_vmware' '--nousepkg'
ERROR   : Backtrace:  (most recent call is last)
ERROR   :  build_packages:368:main(), called: die_err_trap  
ERROR   : 
ERROR   : Command failed:
ERROR   :   Command '( if [[ "${FLAGS_run_goma}" -eq "${FLAGS_TRUE}" ]]; then
ERROR   :     info "Starting goma compiler_proxy."; goma_ctl="${GOMA_DIR:-${HOME}/goma}/goma_ctl.py"; "${goma_ctl}" restart; trap "'${goma_ctl}' stop" EXIT;
ERROR   : fi; GOMA_WRAPPER=(); if [[ "${FLAGS_build_all_with_goma}" -eq "${FLAGS_TRUE}" ]]; then
ERROR   :     warn "The build_all_with_goma feature is still under development."; warn "This feature is experimental and may potentially break your build."; GOMA_WRAPPER=("${GOMA_DIR:-${HOME}/goma}/goma-wrapper" -j600 -l100);
ERROR   : fi; sudo -E "${GOMA_WRAPPER[@]}" "${EMERGE_CMD[@]}" "${EMERGE_FLAGS[@]}" "${PACKAGES[@]}" )' exited with nonzero code: 1
```

**Comment by yunshansimon** [comment]
There is a workaround, insert one line before ` /mnt/host/source/chromite/
scripts/parallel_emerge_old.py line:533`, `pkg.root = root`

**Comment by AdamKearn** [comment]
That solved that problem.
However, I am still getting the Goma issues

```
ERROR   : Tue Aug 13 12:13:09 PDT 2019
ERROR   :   PGID   PPID    PID     ELAPSED     TIME %CPU COMMAND
ERROR   :      7      4      7    21:52:01 00:00:00  0.0 -bash
ERROR   :  80532      7  80532    01:05:11 00:00:00  0.0  \_ /bin/bash ./build_packages --board=amd64-generic_vmware --nousepkg
ERROR   :  80532  80532  93983       00:00 00:00:00  0.0      \_ /bin/bash ./build_packages --board=amd64-generic_vmware --nousepkg
ERROR   :  80532  93983  93984       00:00 00:00:00  0.0          \_ ps f -o pgid,ppid,pid,etime,cputime,%cpu,command
ERROR   : Arguments of 80532: ./build_packages '--board=amd64-generic_vmware' '--nousepkg'
ERROR   : Backtrace:  (most recent call is last)
ERROR   :  build_packages:368:main(), called: die_err_trap  
ERROR   : 
ERROR   : Command failed:
ERROR   :   Command '( if [[ "${FLAGS_run_goma}" -eq "${FLAGS_TRUE}" ]]; then
ERROR   :     info "Starting goma compiler_proxy."; goma_ctl="${GOMA_DIR:-${HOME}/goma}/goma_ctl.py"; "${goma_ctl}" restart; trap "'${goma_ctl}' stop" EXIT;
ERROR   : fi; GOMA_WRAPPER=(); if [[ "${FLAGS_build_all_with_goma}" -eq "${FLAGS_TRUE}" ]]; then
ERROR   :     warn "The build_all_with_goma feature is still under development."; warn "This feature is experimental and may potentially break your build."; GOMA_WRAPPER=("${GOMA_DIR:-${HOME}/goma}/goma-wrapper" -j600 -l100);
ERROR   : fi; sudo -E "${GOMA_WRAPPER[@]}" "${EMERGE_CMD[@]}" "${EMERGE_FLAGS[@]}" "${PACKAGES[@]}" )' exited with nonzero code: 1
```

**Comment by yunshansimon** [comment]
```
# --run_goma option is designed to be used on bots.
# If you're trying to build pacakges with goma in your local dev env, this is
# *not* the option you're looking for. Please see comments below.
# This option; 1) starts goma, 2) builds packages (expecting that goma is
# used), then 3) stops goma explicitly.
# 3) is a request from the goma team, so that stats/logs can be taken.
# Note: GOMA_DIR and GOMA_SERVICE_ACCOUNT_JSON_FILE are expected to be passed
# via env var.
#
# In local dev env cases, compiler_proxy is expected to keep running.
# In such a case;
#   $ python ${GOMA_DIR}/goma_ctl.py ensure_start
#   $ ./build_packages (... and options without --run_goma ...)
# is an expected commandline sequence. If you set --run_goma flag while
# compiler_proxy is already running, the existing compiler_proxy will be
# stopped.
DEFINE_boolean run_goma "${FLAGS_FALSE}" \
  "If set to true, (re)starts goma, builds packages, and then stops goma."

# The above --run_goma option is a configuration flag meant for build bots. It
# only ensures that goma is running and stops goma when build_packages
# completes. This step is to ensure that goma is functional for Chrome's build
# and does *not* cause all packages to be built using goma.
# If you are trying to build packages locally with goma, the option below is
# what you want to use. You must either ensure that goma is running before you
# invoke build_packages with this option by running:
#   $ python ${GOMA_DIR}/goma_ctl.py ensure_start
# OR you may run build_packages with --run_goma in addition to this option.
# Please see the following link for instructions on how to install goma in your
# local dev environment:
# https://g3doc.corp.google.com/devtools/goma/g3doc/how-to-use-goma/how-to-use-goma-chromeos.md#how-to-install-goma-in-host-environment-recommended

DEFINE_boolean build_all_with_goma "${FLAGS_FALSE}" \
  "If set to true, tries to use goma to build all packages. (experimental)"
```
So, check your script file `~/trunck/src/scripts/build_packages` , these flags should be set to false as default.

**Comment by AdamKearn** [comment]
Hmmmm,  I wonder why they were set to `true`.

Later tonight I’ll have a look at that script and check those values.

Do you think I should just delete my VM and build a fresh checkout, as I have never changed anything in the build scripts?

Thanks for your help.
-Adam

**Comment by yunshansimon** [comment]
You never mentioned your compiling environment. The best practice is `repo init` with `release-R75-12105.B`, and `repo sync`.

**Comment by AdamKearn** [comment]
Oh I’ve been using the TOT (Top Of the Tree) release.

I thought if I use the `release-R75-12105.B` I wouldn’t get the latest updates and would have to download new releases every time. Is this correct ?

**Comment by alphato-o** [comment]
Per README, this overlay was only tested under `release-R75-12105.B`. If you are using it under ToT, you'll then have to resolve any build issue that may have come up. Closing this one now.
